export const testimonialDataThree = [
    {
        id: 1,
        name: "Sarah Johnson",
        src: '/images/testimonial/client-img-3-1.png',
        position: "DigitalRevolve Solutions",
        review: "Just Wow, I like the design and their incredible support. I had some queries and the support team replied within just an hour. Thanks for quick reply.",
        title:"Design quality",
        rating: 5,
    },
    {
        id: 2,
        name: "Larry A. Kolb ",
        src: '/images/testimonial/client-img-3-2.png',
        position: "Driftwood Road",
        review: "The results achieved were beyond our expectations. NextPro agency proved to be proven results achievers, consistently delivering measurable impact. ",
        title:"Customer Support",
        rating: 4.5,
    },
    {
        id: 3,
        name: "Sarah Johnson",
        src: '/images/testimonial/client-img-3-3.png',
        position: "DigitalRevolve Solutions",
        review: "I highly recommend to get you started setting up a design system in Figma.  focus on wireframing layouts with nice defaults.",
        title:"Customizibilty",
        rating: 5,
    },
    {
        id: 4,
        name: "Sarah Johnson",
        src: '/images/testimonial/client-img-3-4.png',
        position: "DigitalRevolve Solutions",
        review: "Not only the design is GREAT, but the support is magnificent. Next marketing agency proved to be proven results achievers, consistently delivering measurable impact.",
        title:"Code quality",
        rating: 3.5,
    },
    {
        id: 5,
        name: "Sarah Johnson",
        src: '/images/testimonial/client-img-3-5.png',
        position: "DigitalRevolve Solutions",
        review: "Excellent customer service! Got back right away and fixed my problem loading template!",
        title:"Design quality",
        rating: 4,
    },
    {
        id: 6,
        name: "Larry A. Kolb ",
        src: '/images/testimonial/client-img-3-6.png',
        position: "Driftwood Road",
        review: "The results achieved were beyond our expectations. Next marketing agency proved to be proven results achievers, consistently delivering measurable impact. ",
        title:"Customer Support",
        rating: 4.5,
    },
    {
        id: 7,
        name: "Sarah Johnson",
        src: '/images/testimonial/client-img-3-7.png',
        position: "DigitalRevolve Solutions",
        review: "Excellent customer service! Got back right away and fixed my problem loading template!",
        title:"Design quality",
        rating: 5,
    },
    {
        id: 8,
        name: "Larry A. Kolb ",
        src: '/images/testimonial/client-img-3-8.png',
        position: "Driftwood Road",
        review: "I highly recommend to get you started setting up a design system in Figma.  focus on wireframing layouts with nice defaults.",
        title:"Customer Support",
        rating: 4.5,
    },
    {
        id: 9,
        name: "Sarah Johnson",
        src: '/images/testimonial/client-img-3-1.png',
        position: "DigitalRevolve Solutions",
        review: "Excellent customer service! Got back right away and fixed my problem loading template!",
        title:"Design quality",
        rating: 5,
    },
    {
        id: 10,
        name: "Sarah Johnson",
        src: '/images/testimonial/client-img-3-2.png',
        position: "DigitalRevolve Solutions",
        review: "Not only the design is GREAT, but the support is magnificent. Next marketing agency proved to be proven results achievers, consistently delivering measurable impact.",
        title:"Code quality",
        rating: 3.5,
    },
    {
        id: 11,
        name: "Sarah Johnson",
        src: '/images/testimonial/client-img-3-3.png',
        position: "DigitalRevolve Solutions",
        review: "Just Wow, I like the design and their incredible support. I had some queries and the support team replied within just an hour. Thanks for quick reply.",
        title:"Design quality",
        rating: 4,
    },
    {
        id: 12,
        name: "Sarah Johnson",
        src: '/images/testimonial/client-img-3-4.png',
        position: "DigitalRevolve Solutions",
        review: "The results achieved were beyond our expectations. NextPro agency proved to be proven results achievers, consistently delivering measurable impact. ",
        title:"Design quality",
        rating: 5,
    },
]